[package]
name = "orbital-system"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.4.5"
num = "0.4.2"
rand = "0.8.5"
specs = "0.20.0"
